Sat, 09 Jan 2016 07:42:15:FC_client.py[line:38] INFO Connect Redis OK!
